---
repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.9.1
    hooks:
      - id: commitizen
  #      - id: commitizen-branch
  #        stages: [ push ]
  - repo: local
    hooks:
      - id: generate-api-models
        name: Generate API Models
        entry: bash bin/gen-api-model.sh
        language: system
        pass_filenames: false
        # Run only when files in polarsen/api/ change
        files: ^polarsen/api/(main|models)/.*\.py$
        stages: [pre-commit]
        verbose: true
      - id: update-pr-notes
        name: Update PR with Release Notes
        entry: bash bin/update-pr-notes.sh
        language: system
        pass_filenames: false
        files: ^RELEASE_NOTES\.md$
        stages: [pre-push]
        verbose: true
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.3
    hooks:
      - id: ruff
        language_version: python3.12
        args:
          - --fix
      - id: ruff-format
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.9.7
    hooks:
      - id: uv-lock
