[fr]
start_message = "Bienvenue dans le bot Polarsen !\n\nPour commencer, utilisez la commande /start."
stop_message = "Merci d'avoir utilisé le bot Polarsen !"
help_message = "Pour obtenir de l'aide, utilisez la commande /help."
lang_changed = "Langue changée avec succès en {lang}."
list_chats_btn = "Voir les groupes"
select_chats_btn = "Sélectionner un groupe"
list_chats_resp = """
<b>Liste des groupes disponibles:</b>
{chats}
"""
no_chats = "Aucun groupe disponible. Ajoutez d'abord un groupe en utilisant /add_chat."
last_message = "dernier message"
selected_chat = "Groupe sélectionné : {chat}"
ask_question_btn = "Poser une question"
no_chat_selected = "Aucun groupe sélectionné. Veuillez d'abord sélectionner un groupe en utilisant /selectionner_groupe."
ask_question_prompt = "Veuillez poser votre question (concernant le groupe {chat}):"
select_ai_btn = "Sélectionner l'IA pour vos questions"
selected_model = "Modèle sélectionné : {model}"
unknown_command = "Commande inconnue. Veuillez utiliser /help pour obtenir de l'aide."
enter_api_key = "Veuillez entrer votre clé API for {source}:"
no_model_selected = "Aucun modèle sélectionné. Veuillez sélectionner un modèle en utilisant /select_ai."
cancel_btn = "Annuler"
action_cancelled = "Action annulée."
api_key_empty_error = "Clé API vide. Veuillez entrer une clé API valide."
api_key_saved = "Clé API enregistrée avec succès pour {source}."
feedback_ok_btn = "Résultat correct"
feedback_ko_btn = "Résultat incorrect"
feedback_do_not_know_btn = "Je ne sais pas"
feedback_received = "Merci pour votre retour !"
show_question_context_btn = "Afficher le contexte de la question"
upload_chat = "Envoyer le chat"
upload_chat_error = "Veuillez envoyer un fichier de chat valide."
chat_uploaded = "Historique du chat envoyé avec succès."
error_occurred = "Une erreur est survenue. Veuillez réessayer plus tard."


[en]
start_message = "Welcome to the Polarsen bot!\n\nTo get started, use the /start command."
stop_message = "Thanks for using Polarsen bot!"
help_message = "To get help, use the /help command."
lang_changed = "Language successfully changed to {lang}."
list_chats_btn = "View groups"
select_chats_btn = "Select a group"
no_chats = "No groups available. Please add a group first using /add_chat."
list_chats_resp = """
<b>Available groups:</b>
{chats}
"""
last_message = "last message"
selected_chat = "Selected group: {chat}"
ask_question_btn = "Ask a question"
no_chat_selected = "No group selected. Please select a group first using /select_chats."
ask_question_prompt = "Please ask your question (regarding group {chat}):"
select_ai_btn = "Select AI for your questions"
selected_model = "Selected model: {model}"
unknown_command = "Unknown command. Please use /help for assistance."
enter_api_key = "Please enter your API key for {source}:"
no_model_selected = "No model selected. Please select a model using /select_ai."
cancel_btn = "Cancel"
action_cancelled = "Action cancelled."
api_key_empty_error = "Empty API key. Please enter a valid API key."
api_key_saved = "API key saved successfully for {source}."
feedback_ok_btn = "Correct result"
feedback_ko_btn = "Incorrect result"
feedback_do_not_know_btn = "I don't know"
feedback_received = "Thank you for your feedback!"
show_question_context_btn = "Show question context"
upload_chat = "Upload chat history"
upload_chat_error = "Please upload a valid chat file."
chat_uploaded = "Chat history uploaded successfully."
error_occurred = "An error occurred. Please try again later."